language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
notifications:
  email: false
sudo: false # use a docker worker
addons:
  apt_packages:
  - libgmp-dev
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("GLPK"); Pkg.test("GLPK")'
